// Generated by sample_palette.py — median colours sampled from the renders.
window.PAL = {
 "walnut": {
  "label": "Walnut veneer",
  "hex": "#3E2615",
  "cmyk": "C0 M39 Y66 K76",
  "src": "walnut-suite-03.webp",
  "box": [
   120,
   320,
   220,
   260
  ]
 },
 "walnutLit": {
  "label": "Walnut, lit",
  "hex": "#4D2A18",
  "cmyk": "C0 M45 Y69 K70",
  "src": "walnut-suite-05.webp",
  "box": [
   480,
   150,
   180,
   700
  ]
 },
 "velvet": {
  "label": "Burgundy velvet",
  "hex": "#5F302D",
  "cmyk": "C0 M49 Y53 K63",
  "src": "walnut-suite-05.webp",
  "box": [
   830,
   150,
   230,
   700
  ]
 },
 "marble": {
  "label": "Black marble",
  "hex": "#28251F",
  "cmyk": "C0 M7 Y22 K84",
  "src": "walnut-suite-02.webp",
  "box": [
   700,
   680,
   220,
   50
  ]
 },
 "brass": {
  "label": "Brass accent",
  "hex": "#F7C254",
  "cmyk": "C0 M21 Y66 K3",
  "src": "walnut-suite-03.webp",
  "box": [
   820,
   895,
   90,
   35
  ]
 },
 "linen": {
  "label": "Beige linen",
  "hex": "#917F6B",
  "cmyk": "C0 M12 Y26 K43",
  "src": "walnut-suite-01.webp",
  "box": [
   560,
   770,
   200,
   90
  ]
 },
 "led": {
  "label": "Warm linear light",
  "hex": "#E8A880",
  "cmyk": "C0 M28 Y45 K9",
  "src": "walnut-suite-05.webp",
  "box": [
   700,
   150,
   30,
   700
  ]
 },
 "stone": {
  "label": "Limestone",
  "hex": "#957953",
  "cmyk": "C0 M19 Y44 K42",
  "src": "arched-retreat-01.webp",
  "box": [
   300,
   120,
   120,
   180
  ]
 },
 "floor": {
  "label": "Polished marble floor",
  "hex": "#AC9B80",
  "cmyk": "C0 M10 Y26 K33",
  "src": "arched-retreat-01.webp",
  "box": [
   820,
   860,
   300,
   110
  ]
 },
 "gold": {
  "label": "Gold metalwork",
  "hex": "#916733",
  "cmyk": "C0 M29 Y65 K43",
  "src": "arched-retreat-01.webp",
  "box": [
   780,
   180,
   60,
   40
  ]
 },
 "mosaic": {
  "label": "Lit mosaic niche",
  "hex": "#998661",
  "cmyk": "C0 M12 Y37 K40",
  "src": "arched-retreat-05.webp",
  "box": [
   850,
   420,
   100,
   100
  ]
 },
 "sTimber": {
  "label": "Walnut wall panelling",
  "hex": "#552D14",
  "cmyk": "C0 M47 Y76 K67",
  "src": "skyline-suite-01.webp",
  "box": [
   1490,
   260,
   180,
   220
  ]
 },
 "sTaupe": {
  "label": "Taupe velvet headboard",
  "hex": "#533721",
  "cmyk": "C0 M34 Y60 K67",
  "src": "skyline-suite-01.webp",
  "box": [
   1230,
   528,
   190,
   28
  ]
 },
 "sOak": {
  "label": "Dark oak floor",
  "hex": "#4D2711",
  "cmyk": "C0 M49 Y78 K70",
  "src": "skyline-suite-01.webp",
  "box": [
   1620,
   890,
   150,
   80
  ]
 },
 "sLeather": {
  "label": "Dark leather bench",
  "hex": "#462D1B",
  "cmyk": "C0 M36 Y61 K73",
  "src": "skyline-suite-01.webp",
  "box": [
   840,
   772,
   330,
   18
  ]
 },
 "vStone": {
  "label": "Limestone cladding",
  "hex": "#F1D3B1",
  "cmyk": "C0 M12 Y27 K5",
  "src": "illuminated-villa-05.webp",
  "box": [
   900,
   280,
   200,
   220
  ]
 },
 "vScreen": {
  "label": "Timber screen",
  "hex": "#5C4734",
  "cmyk": "C0 M23 Y43 K64",
  "src": "illuminated-villa-05.webp",
  "box": [
   380,
   300,
   150,
   150
  ]
 },
 "vFascia": {
  "label": "Dark bronze fascia",
  "hex": "#705845",
  "cmyk": "C0 M21 Y38 K56",
  "src": "illuminated-villa-05.webp",
  "box": [
   300,
   505,
   500,
   20
  ]
 },
 "vDoor": {
  "label": "Timber entrance door",
  "hex": "#4C2912",
  "cmyk": "C0 M46 Y76 K70",
  "src": "illuminated-villa-05.webp",
  "box": [
   720,
   620,
   100,
   180
  ]
 },
 "vGlow": {
  "label": "Warm facade light",
  "hex": "#D09A58",
  "cmyk": "C0 M26 Y58 K18",
  "src": "illuminated-villa-04.webp",
  "box": [
   1012,
   360,
   50,
   300
  ]
 },
 "gTimber": {
  "label": "Walnut slats",
  "hex": "#5F412B",
  "cmyk": "C0 M32 Y55 K63",
  "src": "garden-lounge-03.webp",
  "box": [
   200,
   100,
   220,
   400
  ]
 },
 "gTrav": {
  "label": "Travertine",
  "hex": "#AA8966",
  "cmyk": "C0 M19 Y40 K33",
  "src": "garden-lounge-03.webp",
  "box": [
   1000,
   150,
   500,
   220
  ]
 },
 "gBoucle": {
  "label": "Boucle upholstery",
  "hex": "#D6B493",
  "cmyk": "C0 M16 Y31 K16",
  "src": "garden-lounge-05.webp",
  "box": [
   700,
   450,
   250,
   200
  ]
 },
 "gLinen": {
  "label": "Sofa fabric",
  "hex": "#AF8D72",
  "cmyk": "C0 M19 Y35 K31",
  "src": "garden-lounge-01.webp",
  "box": [
   1250,
   675,
   150,
   25
  ]
 },
 "gCharcoal": {
  "label": "Charcoal chair weave",
  "hex": "#382B1E",
  "cmyk": "C0 M23 Y46 K78",
  "src": "garden-lounge-02.webp",
  "box": [
   250,
   730,
   100,
   70
  ]
 },
 "bVelvet": {
  "label": "Burgundy velvet",
  "hex": "#3E1C1C",
  "cmyk": "C0 M55 Y55 K76",
  "src": "burgundy-salon-01.webp",
  "box": [
   850,
   420,
   120,
   160
  ]
 },
 "bTimber": {
  "label": "Walnut panel",
  "hex": "#64432B",
  "cmyk": "C0 M33 Y57 K61",
  "src": "burgundy-salon-01.webp",
  "box": [
   1130,
   400,
   80,
   250
  ]
 },
 "bFloor": {
  "label": "Pale timber floor",
  "hex": "#A69E93",
  "cmyk": "C0 M5 Y11 K35",
  "src": "burgundy-salon-01.webp",
  "box": [
   1300,
   850,
   250,
   80
  ]
 },
 "bWhite": {
  "label": "Gallery wall, in shade",
  "hex": "#9F9E98",
  "cmyk": "C0 M1 Y4 K38",
  "src": "burgundy-salon-01.webp",
  "box": [
   1480,
   560,
   80,
   140
  ]
 },
 "mPlaster": {
  "label": "Textured plaster",
  "hex": "#9D8A70",
  "cmyk": "C0 M12 Y29 K38",
  "src": "earth-toned-majlis-01.webp",
  "box": [
   1100,
   300,
   250,
   200
  ]
 },
 "mOak": {
  "label": "Light oak",
  "hex": "#AA8F70",
  "cmyk": "C0 M16 Y34 K33",
  "src": "earth-toned-majlis-01.webp",
  "box": [
   925,
   300,
   55,
   250
  ]
 },
 "mTerra": {
  "label": "Terracotta",
  "hex": "#7B4E2F",
  "cmyk": "C0 M37 Y62 K52",
  "src": "earth-toned-majlis-03.webp",
  "box": [
   380,
   200,
   100,
   150
  ]
 },
 "mLinen": {
  "label": "Linen seating",
  "hex": "#AA977D",
  "cmyk": "C0 M11 Y26 K33",
  "src": "earth-toned-majlis-01.webp",
  "box": [
   1040,
   664,
   160,
   14
  ]
 },
 "mFrieze": {
  "label": "Frieze pigment",
  "hex": "#87644A",
  "cmyk": "C0 M26 Y45 K47",
  "src": "earth-toned-majlis-03.webp",
  "box": [
   1166,
   596,
   16,
   16
  ]
 },
 "mFloor": {
  "label": "Stone floor",
  "hex": "#C2BAB1",
  "cmyk": "C0 M4 Y9 K24",
  "src": "earth-toned-majlis-01.webp",
  "box": [
   700,
   800,
   300,
   100
  ]
 }
};
