// Generated by sample_palette.py — median colours sampled from the renders.
window.PAL = {
 "walnut": {
  "label": "Walnut veneer",
  "hex": "#3E2615",
  "cmyk": "C0 M39 Y66 K76",
  "src": "walnut-suite-03.webp",
  "box": [
   120,
   320,
   220,
   260
  ]
 },
 "walnutLit": {
  "label": "Walnut, lit",
  "hex": "#4D2A18",
  "cmyk": "C0 M45 Y69 K70",
  "src": "walnut-suite-05.webp",
  "box": [
   480,
   150,
   180,
   700
  ]
 },
 "velvet": {
  "label": "Burgundy velvet",
  "hex": "#5F302D",
  "cmyk": "C0 M49 Y53 K63",
  "src": "walnut-suite-05.webp",
  "box": [
   830,
   150,
   230,
   700
  ]
 },
 "marble": {
  "label": "Black marble",
  "hex": "#28251F",
  "cmyk": "C0 M7 Y22 K84",
  "src": "walnut-suite-02.webp",
  "box": [
   700,
   680,
   220,
   50
  ]
 },
 "brass": {
  "label": "Brass accent",
  "hex": "#F7C254",
  "cmyk": "C0 M21 Y66 K3",
  "src": "walnut-suite-03.webp",
  "box": [
   820,
   895,
   90,
   35
  ]
 },
 "linen": {
  "label": "Beige linen",
  "hex": "#917F6B",
  "cmyk": "C0 M12 Y26 K43",
  "src": "walnut-suite-01.webp",
  "box": [
   560,
   770,
   200,
   90
  ]
 },
 "led": {
  "label": "Warm linear light",
  "hex": "#E8A880",
  "cmyk": "C0 M28 Y45 K9",
  "src": "walnut-suite-05.webp",
  "box": [
   700,
   150,
   30,
   700
  ]
 },
 "stone": {
  "label": "Limestone",
  "hex": "#957953",
  "cmyk": "C0 M19 Y44 K42",
  "src": "arched-retreat-01.webp",
  "box": [
   300,
   120,
   120,
   180
  ]
 },
 "floor": {
  "label": "Polished marble floor",
  "hex": "#AC9B80",
  "cmyk": "C0 M10 Y26 K33",
  "src": "arched-retreat-01.webp",
  "box": [
   820,
   860,
   300,
   110
  ]
 },
 "gold": {
  "label": "Gold metalwork",
  "hex": "#916733",
  "cmyk": "C0 M29 Y65 K43",
  "src": "arched-retreat-01.webp",
  "box": [
   780,
   180,
   60,
   40
  ]
 }
};
