"""Sample real colours from named regions of the project renders → palette.js.
Each chip records its source file and pixel region, so every colour is traceable."""
import json
from pathlib import Path
from PIL import Image
import statistics as st

ROOT = Path(__file__).parent.parent.parent
REGIONS = {
  # key: (label, file, (x, y, w, h))
  'walnut':   ('Walnut veneer',          'projects/walnut-suite-03.webp', (120, 320, 220, 260)),
  'walnutLit':('Walnut, lit',            'projects/walnut-suite-05.webp', (480, 150, 180, 700)),
  'velvet':   ('Burgundy velvet',        'projects/walnut-suite-05.webp', (830, 150, 230, 700)),
  'marble':   ('Black marble',           'projects/walnut-suite-02.webp', (700, 680, 220, 50)),
  'brass':    ('Brass accent',           'projects/walnut-suite-03.webp', (820, 895, 90, 35)),
  'linen':    ('Beige linen',            'projects/walnut-suite-01.webp', (560, 770, 200, 90), 'lit'),
  'led':      ('Warm linear light',      'projects/walnut-suite-05.webp', (700, 150, 30, 700)),
  'stone':    ('Limestone',              'projects/arched-retreat-01.webp', (300, 120, 120, 180), 'lit'),
  'floor':    ('Polished marble floor',  'projects/arched-retreat-01.webp', (820, 860, 300, 110), 'lit'),
  'gold':     ('Gold metalwork',         'projects/arched-retreat-01.webp', (780, 180, 60, 40)),
}
def med(im, box, lit=False):
    x, y, w, h = box
    px = list(im.crop((x, y, x + w, y + h)).convert('RGB').get_flattened_data())
    if lit:  # textured surfaces: median of the lit half, so shadows in the texture don't darken the chip
        px.sort(key=lambda c: 0.299 * c[0] + 0.587 * c[1] + 0.114 * c[2])
        px = px[len(px) // 2:]
    return tuple(int(st.median(c[i] for c in px)) for i in range(3))
def cmyk(r, g, b):
    r, g, b = r / 255, g / 255, b / 255
    k = 1 - max(r, g, b)
    if k >= 1: return (0, 0, 0, 100)
    return tuple(round(100 * v) for v in ((1 - r - k) / (1 - k), (1 - g - k) / (1 - k), (1 - b - k) / (1 - k), k))
out = {}
for key, (label, f, box, *opt) in REGIONS.items():
    rgb = med(Image.open(ROOT / f), box, bool(opt))
    out[key] = {'label': label, 'hex': '#%02X%02X%02X' % rgb, 'cmyk': 'C%d M%d Y%d K%d' % cmyk(*rgb), 'src': f.split('/')[-1], 'box': box}
    print(f'{key:10s} {out[key]["hex"]} {out[key]["cmyk"]:18s} {label}')
Path(__file__).with_name('palette.js').write_text('// Generated by sample_palette.py — median colours sampled from the renders.\nwindow.PAL = ' + json.dumps(out, indent=1) + ';\n')
